name: run-MPI-Checker
on: [push]
jobs:
  run-mpi-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
# install clang-tidy
      - run : sudo apt-get update && sudo apt-get install -y clang-tidy libopenmpi-dev
# setup env or running
      - run: mkdir experiment
      - name: Run CorrBench
        run: |
           MPI_CORRECTNESS_BM_DIR=${GITHUB_WORKSPACE} MPI_CORRECTNESS_BM_EXPERIMENT_DIR=${GITHUB_WORKSPACE}/experiment \
           bash ${GITHUB_WORKSPACE}/scripts/tool_runner_CI.sh MPI-Checker
      - uses: actions/upload-artifact@v2
        with:
          name: results_MPI-Checker
          path: ${{ github.workspace }}/experiment/MPI-Checker/results_MPI-Checker.json

