name: run-MUST
on: [push]
jobs:
  run-must:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
# prerequisites for must
      - run : sudo apt-get update && sudo apt-get install -y \
             git libxml2-dev libopenmpi-dev
# cmake is already installed?
# install MUST
      - run: bash ./scripts/MUST/install_tool.sh
      - run: export PATH=$PATH:${GITHUB_WORKSPACE}/MUST_install/bin
#TODO provide a container with the installation of MUST
# setup env or running
      - run: export MPI_CORRECTNESS_BM_DIR=${GITHUB_WORKSPACE}
      - run: mkdir experiment
      - run: export MPI_CORRECTNESS_BM_EXPERIMENT_DIR=${GITHUB_WORKSPACE}/experiment
      - run: bash ${GITHUB_WORKSPACE}/scripts/tool_runner_CI.sh MUST
      - uses: actions/upload-artifact@v2
        with:
          name: results_MUST
          path: ${GITHUB_WORKSPACE}/experiment/results_MUST.json

