name: run-MUST
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
# prerequisites for must
      - run : sudo apt install -y \
            cmake git libxml2-dev openmpi
# install MUST
      - run: bash ./scripts/MUST/install_tool.sh
      - run: export PATH=$PATH:${GITHUB_WORKSPACE}/MUST_install/bin
# setup env or running
      - run: export MPI_CORRECTNESS_BM_DIR=${GITHUB_WORKSPACE}
      - run: mkdir experiment
      - run: export MPI_CORRECTNESS_BM_EXPERIMENT_DIR=${GITHUB_WORKSPACE}/experiment
      - run: bash ${GITHUB_WORKSPACE}/scripts/tool_runner_CI.sh MUST
      - uses: actions/upload-artifact@v2
        with:
          name: results_MUST
          path: ${GITHUB_WORKSPACE}/experiment/results_MUST.json

